name: Github Actions Demo
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        # run: echo "Hello World! Grettings from github actions demo"
        run: sh ./github-actions-scripts.sh

      - name: Run a multi-line script
        run: |
          echo 1. Nothing to see in the multi-line script.
          echo Here is what in this folder
          ls -a
          
